---
api:
  replicas: 1
app:
  replicas: 1
  domain: api.dev.rovbots.com
  configmap:
    is_production: "false"
    env: "dev"
    port: "3000"
info:
  owner: Somykoron
  contact: support@somykoron.com
  project: rovbots